<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\BalkisHassan.Domain\BalkisHassan.Domain.csproj" />
    <ProjectReference Include="..\..\src\BalkisHassan.Infrastructure\BalkisHassan.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HtmlSanitizer" Version="9.2.1039" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.12" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>3da29823-81dd-4640-815e-85c7c35be6b1</UserSecretsId>
  </PropertyGroup>

</Project>
